### ISSUE TITLE
Resize UI to read full paths + command line version maybe??

### ISSUE THREAD

**Issue by M4RCK5** [PrismaticFlower/lvl-repack#1]
Idk if the repacking process finished, i wanted to read the last filename from the left but even resizing the window i still cant see the file name. Can we have it as an CLI tool?? i want to run it trough a batch script.
![image](https://github.com/PrismaticFlower/lvl-repack/assets/20927212/fbe35447-b2f9-46e0-bd66-ece8efe372b1)

**Comment by PrismaticFlower** [comment]
The UI could definitely stand to be a lot better. It was thrown together very quickly. You can even see where I placed a progress bar but forgot to connect it up to anything.

I'm happy to say though that all `lvl-repack.exe` is doing is launching the command line tool `repack.exe` for each file. So you can absolutely skip `lvl-repack.exe` and use `repack.exe` directly yourself. The usage should be very straightforward: `repack <file>` or `repack <file> prefer_compessed_textures`.

**Comment by M4RCK5** [comment]
> I'm happy to say though that all `lvl-repack.exe` is doing is launching the command line tool `repack.exe` for each file. So you can absolutely skip `lvl-repack.exe` and use `repack.exe` directly yourself. The usage should be very straightforward: `repack <file>` or `repack <file> prefer_compessed_textures`.

Cool i was thinking on making a batch script that uses a loop to find all the files ending in ".lvl" witting a path so i can drag and drop into the script window itself.

```
@echo off
title lvl-repack
cd /d "%~dp0"

:start
call :title
set "input="
set /p "input=Folder: "
if defined input set "input=%input:"=%" else goto start
if not exist "%input%" goto start

echo.
set "compress="
choice /c yn /n /m "Texture compression (Y/N)? "
if %errorlevel% equ 1 set "compress=prefer_compessed_textures"

call :title
for /r "%input%" %%a in (*.lvl) do repack.exe "%%~fa" %compress%
pause
goto start

:title
cls
echo.
echo ----lvl-repack----
echo.
goto :eof
```
